service: blog-api # NOTE: update this with your service name

plugins:
  - serverless-webpack
  - serverless-mocha-plugin

custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-northeast-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"

functions:
  delete:
    handler: delete.main
    events:
      - http:
          path: entries/{id}
          method: delete
          cors: true
          authorizer:
            arn: "${self:custom.secrets.COMMON_USER_POOL_ARN}"
  update:
    handler: update.main
    events:
      - http:
          path: entries/{id}
          method: put
          cors: true
          authorizer:
            arn: "${self:custom.secrets.COMMON_USER_POOL_ARN}"
  list:
    handler: list.main
    events:
      - http:
          path: entries
          method: get
          cors: true
          authorizer:
            arn: "${self:custom.secrets.COMMON_USER_POOL_ARN}"
  get:
    handler: get.main
    events:
      - http:
          path: entries/{id}
          method: get
          cors: true
          authorizer:
            arn: "${self:custom.secrets.COMMON_USER_POOL_ARN}"
  create:
    handler: create.main
    events:
      - http:
          path: entries
          method: post
          cors: true
          authorizer:
            arn: "${self:custom.secrets.COMMON_USER_POOL_ARN}"

